<?php

namespace App\Http\Requests\Payment;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Starts a local development payment simulation.
 *
 * The client never supplies the amount, result, or provider transaction id:
 * those values are derived/generated by PaymentService. A real deployment
 * must replace this endpoint with a provider checkout + signed webhook flow.
 */
class ConfirmPaymentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    public function rules(): array
    {
        return [
            'provider' => ['sometimes', Rule::in(['local_mock'])],
        ];
    }
}
